// <auto-generated />
using System;
using MachineShopApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MachineShopApi.Migrations
{
    [DbContext(typeof(MachineShopContext))]
    [Migration("20251123053447_RevisionBD")]
    partial class RevisionBD
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("MachineShopApi.Models.Area", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("IdArea");

                    b.Property<string>("NombreArea")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ResponsableAreaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ResponsableAreaId");

                    b.ToTable("Areas");
                });

            modelBuilder.Entity("MachineShopApi.Models.EstadoTrabajo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("IdEstado");

                    b.Property<string>("DescripcionOperacion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaYHoraDeFin")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaYHoraDeInicio")
                        .HasColumnType("TEXT");

                    b.Property<int>("IdMaquinista")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdSolicitud")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MaquinaAsignada")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Observaciones")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TiempoMaquina")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("Id");

                    b.HasIndex("IdMaquinista");

                    b.HasIndex("IdSolicitud");

                    b.ToTable("EstadoTrabajo");
                });

            modelBuilder.Entity("MachineShopApi.Models.Pieza", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("IdPieza");

                    b.Property<int>("IdArea")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Maquina")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Máquina")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NombrePieza")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IdArea");

                    b.ToTable("Piezas");
                });

            modelBuilder.Entity("MachineShopApi.Models.Revision", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("IdRevision");

                    b.Property<string>("Comentarios")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaHoraRevision")
                        .HasColumnType("TEXT");

                    b.Property<int>("IdRevisor")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdSolicitud")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Prioridad")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IdRevisor");

                    b.HasIndex("IdSolicitud")
                        .IsUnique();

                    b.ToTable("Revisiones");
                });

            modelBuilder.Entity("MachineShopApi.Models.Solicitud", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("IdSolicitud");

                    b.Property<string>("Detalles")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Dibujo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaYHora")
                        .HasColumnType("TEXT");

                    b.Property<int>("IdPieza")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SolicitanteId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Turno")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IdPieza");

                    b.HasIndex("SolicitanteId");

                    b.ToTable("Solicitudes");
                });

            modelBuilder.Entity("MachineShopApi.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("IdUsuario");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Area")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            Area = "Ingeniería",
                            Email = "system@molex.com",
                            Nombre = "Revisión de Ingeniería",
                            PasswordHash = "SYSTEM_RESERVED",
                            Rol = "Sistema"
                        });
                });

            modelBuilder.Entity("MachineShopApi.Models.Area", b =>
                {
                    b.HasOne("MachineShopApi.Models.Usuario", "ResponsableArea")
                        .WithMany("AreasResponsables")
                        .HasForeignKey("ResponsableAreaId");

                    b.Navigation("ResponsableArea");
                });

            modelBuilder.Entity("MachineShopApi.Models.EstadoTrabajo", b =>
                {
                    b.HasOne("MachineShopApi.Models.Usuario", "Maquinista")
                        .WithMany()
                        .HasForeignKey("IdMaquinista")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MachineShopApi.Models.Solicitud", "Solicitud")
                        .WithMany("Operaciones")
                        .HasForeignKey("IdSolicitud")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Maquinista");

                    b.Navigation("Solicitud");
                });

            modelBuilder.Entity("MachineShopApi.Models.Pieza", b =>
                {
                    b.HasOne("MachineShopApi.Models.Area", "Area")
                        .WithMany("Piezas")
                        .HasForeignKey("IdArea")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Area");
                });

            modelBuilder.Entity("MachineShopApi.Models.Revision", b =>
                {
                    b.HasOne("MachineShopApi.Models.Usuario", "Revisor")
                        .WithMany("RevisionesRealizadas")
                        .HasForeignKey("IdRevisor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MachineShopApi.Models.Solicitud", "Solicitud")
                        .WithOne("Revision")
                        .HasForeignKey("MachineShopApi.Models.Revision", "IdSolicitud")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Revisor");

                    b.Navigation("Solicitud");
                });

            modelBuilder.Entity("MachineShopApi.Models.Solicitud", b =>
                {
                    b.HasOne("MachineShopApi.Models.Pieza", "Pieza")
                        .WithMany("Solicitudes")
                        .HasForeignKey("IdPieza")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MachineShopApi.Models.Usuario", "Solicitante")
                        .WithMany("SolicitudesRealizadas")
                        .HasForeignKey("SolicitanteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Pieza");

                    b.Navigation("Solicitante");
                });

            modelBuilder.Entity("MachineShopApi.Models.Area", b =>
                {
                    b.Navigation("Piezas");
                });

            modelBuilder.Entity("MachineShopApi.Models.Pieza", b =>
                {
                    b.Navigation("Solicitudes");
                });

            modelBuilder.Entity("MachineShopApi.Models.Solicitud", b =>
                {
                    b.Navigation("Operaciones");

                    b.Navigation("Revision");
                });

            modelBuilder.Entity("MachineShopApi.Models.Usuario", b =>
                {
                    b.Navigation("AreasResponsables");

                    b.Navigation("RevisionesRealizadas");

                    b.Navigation("SolicitudesRealizadas");
                });
#pragma warning restore 612, 618
        }
    }
}
