// <auto-generated />
using System;
using MachineShopApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MachineShopApi.Migrations
{
    [DbContext(typeof(MachineShopContext))]
    [Migration("20251121072852_InitialSqliteMigration")]
    partial class InitialSqliteMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("MachineShopApi.Models.Area", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("IdArea");

                    b.Property<string>("NombreArea")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ResponsableAreaId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ResponsableAreaId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Areas");
                });

            modelBuilder.Entity("MachineShopApi.Models.EstadoTrabajo", b =>
                {
                    b.Property<int>("IdEstado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaHoraInicio")
                        .HasColumnType("TEXT");

                    b.Property<int?>("IdMaquinista")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdSolicitud")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MaquinaAsignada")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Observaciones")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan?>("TiempoMaquina")
                        .HasColumnType("TEXT");

                    b.HasKey("IdEstado");

                    b.HasIndex("IdMaquinista");

                    b.HasIndex("IdSolicitud")
                        .IsUnique();

                    b.ToTable("EstadoTrabajos");
                });

            modelBuilder.Entity("MachineShopApi.Models.Pieza", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("IdPieza");

                    b.Property<int>("IdArea")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Maquina")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("NombrePieza")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IdArea");

                    b.ToTable("Piezas");
                });

            modelBuilder.Entity("MachineShopApi.Models.Revision", b =>
                {
                    b.Property<int>("IdRevision")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Comentarios")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EstadoRevision")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaHoraRevision")
                        .HasColumnType("TEXT");

                    b.Property<int>("IdRevisor")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdSolicitud")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NivelUrgencia")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdRevision");

                    b.HasIndex("IdRevisor");

                    b.HasIndex("IdSolicitud")
                        .IsUnique();

                    b.HasIndex("UsuarioId");

                    b.ToTable("Revisiones");
                });

            modelBuilder.Entity("MachineShopApi.Models.Solicitud", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("IdSolicitud");

                    b.Property<string>("Detalles")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Dibujo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EstadoActual")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaYHora")
                        .HasColumnType("TEXT");

                    b.Property<int>("IdPieza")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Prioridad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SolicitanteId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Turno")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IdPieza");

                    b.HasIndex("SolicitanteId");

                    b.ToTable("Solicitudes");
                });

            modelBuilder.Entity("MachineShopApi.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("IdUsuario");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Area")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("MachineShopApi.Models.Area", b =>
                {
                    b.HasOne("MachineShopApi.Models.Usuario", "ResponsableArea")
                        .WithMany()
                        .HasForeignKey("ResponsableAreaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MachineShopApi.Models.Usuario", null)
                        .WithMany("AreasResponsables")
                        .HasForeignKey("UsuarioId");

                    b.Navigation("ResponsableArea");
                });

            modelBuilder.Entity("MachineShopApi.Models.EstadoTrabajo", b =>
                {
                    b.HasOne("MachineShopApi.Models.Usuario", "Maquinista")
                        .WithMany()
                        .HasForeignKey("IdMaquinista")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MachineShopApi.Models.Solicitud", "Solicitud")
                        .WithOne("EstadoTrabajo")
                        .HasForeignKey("MachineShopApi.Models.EstadoTrabajo", "IdSolicitud")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Maquinista");

                    b.Navigation("Solicitud");
                });

            modelBuilder.Entity("MachineShopApi.Models.Pieza", b =>
                {
                    b.HasOne("MachineShopApi.Models.Area", "Area")
                        .WithMany("Piezas")
                        .HasForeignKey("IdArea")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Area");
                });

            modelBuilder.Entity("MachineShopApi.Models.Revision", b =>
                {
                    b.HasOne("MachineShopApi.Models.Usuario", "Revisor")
                        .WithMany()
                        .HasForeignKey("IdRevisor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MachineShopApi.Models.Solicitud", "Solicitud")
                        .WithOne("Revision")
                        .HasForeignKey("MachineShopApi.Models.Revision", "IdSolicitud")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MachineShopApi.Models.Usuario", null)
                        .WithMany("RevisionesRealizadas")
                        .HasForeignKey("UsuarioId");

                    b.Navigation("Revisor");

                    b.Navigation("Solicitud");
                });

            modelBuilder.Entity("MachineShopApi.Models.Solicitud", b =>
                {
                    b.HasOne("MachineShopApi.Models.Pieza", "Pieza")
                        .WithMany("Solicitudes")
                        .HasForeignKey("IdPieza")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MachineShopApi.Models.Usuario", "Solicitante")
                        .WithMany("SolicitudesRealizadas")
                        .HasForeignKey("SolicitanteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Pieza");

                    b.Navigation("Solicitante");
                });

            modelBuilder.Entity("MachineShopApi.Models.Area", b =>
                {
                    b.Navigation("Piezas");
                });

            modelBuilder.Entity("MachineShopApi.Models.Pieza", b =>
                {
                    b.Navigation("Solicitudes");
                });

            modelBuilder.Entity("MachineShopApi.Models.Solicitud", b =>
                {
                    b.Navigation("EstadoTrabajo");

                    b.Navigation("Revision");
                });

            modelBuilder.Entity("MachineShopApi.Models.Usuario", b =>
                {
                    b.Navigation("AreasResponsables");

                    b.Navigation("RevisionesRealizadas");

                    b.Navigation("SolicitudesRealizadas");
                });
#pragma warning restore 612, 618
        }
    }
}
